version: '3.9'

services:
  predictor-service:
    build: ./predictor-service
    container_name: predictor
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/shared
    environment:
      - MODEL_PATH=/shared/model.pkl

  streamlit-ui:
    build: ./streamlit-ui
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - predictor-service
    environment:
      - PREDICT_URL=http://predictor:8000/predict
    volumes:
      - ./shared:/shared
