version: '3.9'

services:
  predictor-service:
    build: ./predictor-service
    container_name: predictor
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/shared
    environment:
      - MODEL_PATH=/shared/model.pkl
