name: 🚀 Deploy HTML Report to GitHub Pages

on:
  push:
    branches: [main]  # or your default branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r mlflow/requirements.txt

      - name: Run prediction and generate report
        run: python mlflow/log_run.py

      - name: Push to gh-pages
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
         git push origin --force gh-pages

