name: Run MLOps Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow
        ports:
          - 5000:5000
        options: --name mlflow-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for MLflow to start
        run: |
          sleep 10  # Give the container time to start

      - name: Run MLflow logging script
        run: |
          python mlflow/log_run.py
      - name: Create report
        run: |
          echo "### Prediction Logged" > report.md
          echo "📌 Sample Transaction: ${GITHUB_RUN_ID}" >> report.md
          echo "✅ Status: Logged to MLflow local store (/tmp/mlruns)" >> report.md
          echo "🔗 Model: KNeighborsClassifier" >> report.md

      - name: Upload summary as artifact
        uses: actions/upload-artifact@v4
        with:
         name: mlflow-report
         path: report.md

